In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import mean_squared_error

In [2]:
traindata = pd.read_csv('train_FD001.txt',sep=' ',header = None)
testdata = pd.read_csv('test_FD001.txt',sep=' ',header = None)
RULdata = pd.read_csv('RUL_FD001.txt',sep=' ',header = None)

# Making a readable dataset
columns = {0:'engineNumber',1:'cycleNumber',2:'opSetting1',3:'opSetting2',4:'opSetting3',5:'sensor1',6:'sensor2',
           7:'sensor3',8:'sensor4',9:'sensor5',10:'sensor6',11:'sensor7',12:'sensor8',13:'sensor9',14:'sensor10',
           15:'sensor11',16:'sensor12',17:'sensor13',18:'sensor14',19:'sensor15',20:'sensor16',
           21:'sensor17',22:'sensor18',23:'sensor19',24:'sensor20',25:'sensor21'}

train_data = traindata.rename(columns=columns)
test_data = testdata.rename(columns=columns)
true_rul = RULdata.rename(columns={0: 'RUL'})

In [3]:
num_cycles_to_failure = train_data.groupby('engineNumber')['cycleNumber'].count()
num_cycles_to_failure

engineNumber
1      192
2      287
3      179
4      189
5      269
      ...
96     336
97     202
98     156
99     185
100    200
Name: cycleNumber, Length: 100, dtype: int64

In [4]:
selcted_train_data = pd.DataFrame([train_data['sensor2'],train_data['sensor3'],train_data['sensor4'],train_data['sensor7'],train_data['sensor8'],train_data['sensor9'],train_data['sensor11'],train_data['sensor12'],train_data['sensor13'],train_data['sensor15'],train_data['sensor17'],train_data['sensor20'],train_data['sensor21']])
selected_train_data =selcted_train_data.transpose()
selected_train_data

,sensor2,sensor3,sensor4,sensor7,sensor8,sensor9,sensor11,sensor12,sensor13,sensor15,sensor17,sensor20,sensor21
0,641.82,1589.70,1400.60,554.36,2388.06,9046.19,47.47,521.66,2388.02,8.4195,392.0,39.06,23.4190
1,642.15,1591.82,1403.14,553.75,2388.04,9044.07,47.49,522.28,2388.07,8.4318,392.0,39.00,23.4236
2,642.35,1587.99,1404.20,554.26,2388.08,9052.94,47.27,522.42,2388.03,8.4178,390.0,38.95,23.3442
3,642.35,1582.79,1401.87,554.45,2388.11,9049.48,47.13,522.86,2388.08,8.3682,392.0,38.88,23.3739
4,642.37,1582.85,1406.22,554.00,2388.06,9055.15,47.28,522.19,2388.04,8.4294,393.0,38.90,23.4044
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20626,643.49,1597.98,1428.63,551.43,2388.19,9065.52,48.07,519.49,2388.26,8.4956,397.0,38.49,22.9735
20627,643.54,1604.50,1433.58,550.86,2388.23,9065.11,48.04,519.68,2388.22,8.5139,395.0,38.30,23.1594
20628,643.42,1602.46,1428.18,550.94,2388.24,9065.90,48.09,520.01,2388.24,8.5646,398.0,38.44,22.9333
20629,643.23,1605.26,1426.53,550.68,2388.25,9073.72,48.39,519.67,2388.23,8.5389,395.0,38.29,23.0640
20630,643.85,1600.38,1432.14,550.79,2388.26,9061.48,48.20,519.30,2388.26,8.5036,396.0,38.37,23.0522

In [5]:
object = StandardScaler()
scaled_train_data = object.fit_transform(selected_train_data)
scaled_train_data = pd.DataFrame(scaled_train_data)
scaled_train_data

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,-1.721725,-0.134255,-0.925936,1.121141,-0.516338,-0.862813,-0.266467,0.334262,-1.058890,-0.603816,-0.781710,1.348493,1.194427
1,-1.061780,0.211528,-0.643726,0.431930,-0.798093,-0.958818,-0.191583,1.174899,-0.363646,-0.275852,-0.781710,1.016528,1.236922
2,-0.661813,-0.413166,-0.525953,1.008155,-0.234584,-0.557139,-1.015303,1.364721,-0.919841,-0.649144,-2.073094,0.739891,0.503423
3,-0.661813,-1.261314,-0.784831,1.222827,0.188048,-0.713826,-1.539489,1.961302,-0.224597,-1.971665,-0.781710,0.352598,0.777792
4,-0.621816,-1.251528,-0.301518,0.714393,-0.516338,-0.457059,-0.977861,1.052871,-0.780793,-0.339845,-0.136018,0.463253,1.059552
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20626,1.618000,1.216258,2.188375,-2.189329,1.315066,0.012547,1.980044,-2.607969,2.278282,1.425294,2.446751,-1.805173,-2.921113
20627,1.717992,2.279706,2.738351,-2.833345,1.878576,-0.006020,1.867718,-2.350355,1.722087,1.913240,1.155367,-2.856395,-1.203764
20628,1.478011,1.946971,2.138377,-2.742957,2.019453,0.029755,2.054927,-1.902919,2.000184,3.265092,3.092444,-2.081810,-3.292481
20629,1.098043,2.403666,1.955051,-3.036719,2.160330,0.383884,3.178182,-2.363913,1.861136,2.579834,1.155367,-2.911722,-2.085072
20630,2.337940,1.607712,2.578358,-2.912435,2.301208,-0.170405,2.466787,-2.865584,2.278282,1.638604,1.801059,-2.469103,-2.194080

In [6]:
EOL = []
for sl_no in train_data['engineNumber']:
    EOL.append( ( (train_data[train_data['engineNumber'] == sl_no]['cycleNumber']).values)[-1])

In [7]:
Y = EOL-train_data['cycleNumber']
Y

0        191
1        190
2        189
3        188
4        187
        ...
20626      4
20627      3
20628      2
20629      1
20630      0
Name: cycleNumber, Length: 20631, dtype: int64

In [8]:
selcted_test_data = pd.DataFrame([test_data['sensor2'],test_data['sensor3'],test_data['sensor4'],test_data['sensor7'],test_data['sensor8'],test_data['sensor9'],test_data['sensor11'],test_data['sensor12'],test_data['sensor13'],test_data['sensor15'],test_data['sensor17'],test_data['sensor20'],test_data['sensor21']])
selected_test_data =selcted_test_data.transpose()
selected_test_data

,sensor2,sensor3,sensor4,sensor7,sensor8,sensor9,sensor11,sensor12,sensor13,sensor15,sensor17,sensor20,sensor21
0,643.02,1585.29,1398.21,553.90,2388.04,9050.17,47.20,521.72,2388.03,8.4052,392.0,38.86,23.3735
1,641.71,1588.45,1395.42,554.85,2388.01,9054.42,47.50,522.16,2388.06,8.3803,393.0,39.02,23.3916
2,642.46,1586.94,1401.34,554.11,2388.05,9056.96,47.50,521.97,2388.03,8.4441,393.0,39.08,23.4166
3,642.44,1584.12,1406.42,554.07,2388.03,9045.29,47.28,521.38,2388.05,8.3917,391.0,39.00,23.3737
4,642.51,1587.19,1401.92,554.16,2388.01,9044.55,47.31,522.15,2388.03,8.4031,390.0,38.99,23.4130
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13091,643.24,1599.45,1415.79,553.41,2388.02,9142.37,47.69,520.69,2388.00,8.4715,394.0,38.65,23.1974
13092,643.22,1595.69,1422.05,553.22,2388.05,9140.68,47.60,521.05,2388.09,8.4512,395.0,38.57,23.2771
13093,643.44,1593.15,1406.82,553.04,2388.11,9146.81,47.57,521.18,2388.04,8.4569,395.0,38.62,23.2051
13094,643.26,1594.99,1419.36,553.37,2388.07,9148.85,47.61,521.33,2388.08,8.4711,395.0,38.66,23.2699
13095,642.95,1601.62,1424.99,552.48,2388.06,9155.03,47.80,521.07,2388.05,8.4903,396.0,38.70,23.1855

In [9]:
scaled_test_data = object.fit_transform(selected_test_data)
scaled_test_data = pd.DataFrame(scaled_test_data)
scaled_test_data

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,1.359276,-0.561495,-0.975674,0.209138,-0.539078,-0.720312,-1.103591,-0.049542,-0.720590,-0.711659,-0.463406,-0.229408,0.448866
1,-1.908502,0.070116,-1.392836,1.603612,-1.061366,-0.348673,0.427727,0.736727,-0.193647,-1.570037,0.347276,0.899934,0.664042
2,-0.037636,-0.231698,-0.507676,0.517390,-0.364982,-0.126564,0.427727,0.397202,-0.720590,0.629340,0.347276,1.323438,0.961247
3,-0.087526,-0.795350,0.251888,0.458675,-0.713174,-1.147041,-0.695239,-0.657113,-0.369295,-1.177045,-1.274088,0.758766,0.451244
4,0.087088,-0.181729,-0.420954,0.590783,-1.061366,-1.211750,-0.542108,0.718857,-0.720590,-0.784053,-2.084769,0.688182,0.918450
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13091,1.908063,2.268760,1.652893,-0.510118,-0.887270,7.342072,1.397561,-1.890124,-1.247533,1.573900,1.157958,-1.711671,-1.644645
13092,1.858174,1.517224,2.588890,-0.789013,-0.364982,7.194290,0.938166,-1.246814,0.333296,0.874098,1.968639,-2.276342,-0.697156
13093,2.406961,1.009537,0.311696,-1.053229,0.679594,7.730325,0.785034,-1.014507,-0.544942,1.070594,1.968639,-1.923422,-1.553106
13094,1.957953,1.377310,2.186681,-0.568833,-0.016790,7.908712,0.989210,-0.746461,0.157648,1.560111,1.968639,-1.641087,-0.782751
13095,1.184662,2.702493,3.028480,-1.875235,-0.190886,8.449119,1.959044,-1.211074,-0.369295,2.221992,2.779321,-1.358751,-1.786114

In [10]:
EOL2=true_rul.drop([1],axis = 'columns')
EOL2

    RUL
0   112
1    98
2    69
3    82
4    91
..  ...
95  137
96   82
97   59
98  117
99   20

[100 rows x 1 columns]

In [11]:
num_cycles_to_failure2 = test_data.groupby('engineNumber')['cycleNumber'].count()
num_cycles_to_failure2

engineNumber
1       31
2       49
3      126
4      106
5       98
      ...
96      97
97     134
98     121
99      97
100    198
Name: cycleNumber, Length: 100, dtype: int64

In [12]:
nctf = np.array(num_cycles_to_failure2)

In [13]:
EOL2['nofcyc'] = nctf
EOL2

    RUL  nofcyc
0   112      31
1    98      49
2    69     126
3    82     106
4    91      98
..  ...     ...
95  137      97
96   82     134
97   59     121
98  117      97
99   20     198

[100 rows x 2 columns]

In [14]:
EOL2['total'] = EOL2['RUL'] + EOL2['nofcyc']
EOL2

    RUL  nofcyc  total
0   112      31    143
1    98      49    147
2    69     126    195
3    82     106    188
4    91      98    189
..  ...     ...    ...
95  137      97    234
96   82     134    216
97   59     121    180
98  117      97    214
99   20     198    218

[100 rows x 3 columns]

In [15]:
EOL3 = []
for sl_no in test_data['engineNumber']:
    EOL3.append( ( (test_data[test_data['engineNumber'] == sl_no]['cycleNumber']).values)[-1])
    
EOL3

[31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 126,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 106,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 98,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 160,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 ...]

In [16]:
subdata1 = pd.DataFrame(test_data['engineNumber'])
subdata1

       engineNumber
0                 1
1                 1
2                 1
3                 1
4                 1
...             ...
13091           100
13092           100
13093           100
13094           100
13095           100

[13096 rows x 1 columns]

In [17]:
EOL5 =[]
# for i in range(1,101) :
for i in subdata1['engineNumber']:
    EOL5.append(EOL2['total'][i-1])
EOL5

[143,
 143,
 143,
 143,
 143,
 143,
 143,
 143,
 143,
 143,
 143,
 143,
 143,
 143,
 143,
 143,
 143,
 143,
 143,
 143,
 143,
 143,
 143,
 143,
 143,
 143,
 143,
 143,
 143,
 143,
 143,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 147,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 195,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 188,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 198,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 251,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 261,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 ...]

In [18]:
EOL6 = EOL5 - test_data['cycleNumber']
EOL6

0        142
1        141
2        140
3        139
4        138
        ...
13091     24
13092     23
13093     22
13094     21
13095     20
Name: cycleNumber, Length: 13096, dtype: int64

# ANN

In [19]:
ann = tf.keras.models.Sequential()

In [20]:
ann.add(tf.keras.layers.Dense(units=20, activation='relu'))

In [21]:
ann.add(tf.keras.layers.Dense(units=20, activation='relu'))

In [22]:
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))

In [23]:
ann.add(tf.keras.layers.Dense(units=1))

In [24]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

In [25]:
ann.fit(scaled_train_data, Y ,batch_size = 32, epochs = 100,verbose=2)

Epoch 1/100
645/645 - 1s - loss: 5548.2617 - 867ms/epoch - 1ms/step
Epoch 2/100
645/645 - 0s - loss: 1916.5386 - 432ms/epoch - 670us/step
Epoch 3/100
645/645 - 0s - loss: 1855.2198 - 468ms/epoch - 725us/step
Epoch 4/100
645/645 - 0s - loss: 1835.2004 - 462ms/epoch - 716us/step
Epoch 5/100
645/645 - 0s - loss: 1785.7236 - 451ms/epoch - 699us/step
Epoch 6/100
645/645 - 0s - loss: 1763.7578 - 450ms/epoch - 697us/step
Epoch 7/100
645/645 - 0s - loss: 1756.3707 - 439ms/epoch - 681us/step
Epoch 8/100
645/645 - 0s - loss: 1747.4385 - 451ms/epoch - 700us/step
Epoch 9/100
645/645 - 0s - loss: 1746.5209 - 460ms/epoch - 714us/step
Epoch 10/100
645/645 - 0s - loss: 1742.9326 - 467ms/epoch - 724us/step
Epoch 11/100
645/645 - 0s - loss: 1739.1027 - 463ms/epoch - 718us/step
Epoch 12/100
645/645 - 0s - loss: 1735.2146 - 460ms/epoch - 713us/step
Epoch 13/100
645/645 - 0s - loss: 1737.1088 - 447ms/epoch - 693us/step
Epoch 14/100
645/645 - 0s - loss: 1734.9694 - 429ms/epoch - 665us/step
Epoch 15/100
645/645 - 0s - loss: 1736.9208 - 468ms/epoch - 726us/step
Epoch 16/100
645/645 - 1s - loss: 1734.2833 - 587ms/epoch - 909us/step
Epoch 17/100
645/645 - 1s - loss: 1732.7007 - 792ms/epoch - 1ms/step
Epoch 18/100
645/645 - 1s - loss: 1733.8337 - 558ms/epoch - 864us/step
Epoch 19/100
645/645 - 1s - loss: 1730.9836 - 550ms/epoch - 852us/step
Epoch 20/100
645/645 - 0s - loss: 1729.4241 - 492ms/epoch - 763us/step
Epoch 21/100
645/645 - 0s - loss: 1729.9183 - 465ms/epoch - 721us/step
Epoch 22/100
645/645 - 1s - loss: 1727.6041 - 520ms/epoch - 806us/step
Epoch 23/100
645/645 - 1s - loss: 1727.2091 - 631ms/epoch - 978us/step
Epoch 24/100
645/645 - 1s - loss: 1727.3490 - 570ms/epoch - 883us/step
Epoch 25/100
645/645 - 0s - loss: 1726.4081 - 461ms/epoch - 715us/step
Epoch 26/100
645/645 - 1s - loss: 1725.6198 - 600ms/epoch - 930us/step
Epoch 27/100
645/645 - 0s - loss: 1726.2601 - 439ms/epoch - 681us/step
Epoch 28/100
645/645 - 1s - loss: 1724.5109 - 575ms/epoch - 892us/step
Epoch 29/100
645/645 - 0s - loss: 1724.6212 - 492ms/epoch - 763us/step
Epoch 30/100
645/645 - 0s - loss: 1723.7318 - 485ms/epoch - 753us/step
Epoch 31/100
645/645 - 1s - loss: 1722.0374 - 518ms/epoch - 803us/step
Epoch 32/100
645/645 - 1s - loss: 1720.5603 - 600ms/epoch - 930us/step
Epoch 33/100
645/645 - 0s - loss: 1719.3668 - 479ms/epoch - 742us/step
Epoch 34/100
645/645 - 1s - loss: 1716.6127 - 592ms/epoch - 918us/step
Epoch 35/100
645/645 - 1s - loss: 1715.6320 - 518ms/epoch - 803us/step
Epoch 36/100
645/645 - 1s - loss: 1716.0798 - 621ms/epoch - 963us/step
Epoch 37/100
645/645 - 1s - loss: 1716.0267 - 503ms/epoch - 779us/step
Epoch 38/100
645/645 - 1s - loss: 1714.9534 - 506ms/epoch - 785us/step
Epoch 39/100
645/645 - 0s - loss: 1714.1046 - 468ms/epoch - 725us/step
Epoch 40/100
645/645 - 0s - loss: 1711.5491 - 454ms/epoch - 705us/step
Epoch 41/100
645/645 - 0s - loss: 1712.2288 - 467ms/epoch - 725us/step
Epoch 42/100
645/645 - 0s - loss: 1710.8726 - 463ms/epoch - 718us/step
Epoch 43/100
645/645 - 0s - loss: 1709.6753 - 453ms/epoch - 703us/step
Epoch 44/100
645/645 - 0s - loss: 1708.3822 - 467ms/epoch - 724us/step
Epoch 45/100
645/645 - 1s - loss: 1711.0748 - 569ms/epoch - 881us/step
Epoch 46/100
645/645 - 1s - loss: 1708.5148 - 596ms/epoch - 924us/step
Epoch 47/100
645/645 - 1s - loss: 1705.4640 - 549ms/epoch - 852us/step
Epoch 48/100
645/645 - 0s - loss: 1706.5486 - 466ms/epoch - 722us/step
Epoch 49/100
645/645 - 0s - loss: 1702.8092 - 467ms/epoch - 724us/step
Epoch 50/100
645/645 - 0s - loss: 1702.9612 - 460ms/epoch - 712us/step
Epoch 51/100
645/645 - 0s - loss: 1703.0852 - 472ms/epoch - 732us/step
Epoch 52/100
645/645 - 1s - loss: 1701.7045 - 543ms/epoch - 842us/step
Epoch 53/100
645/645 - 1s - loss: 1702.9049 - 619ms/epoch - 960us/step
Epoch 54/100
645/645 - 0s - loss: 1701.9105 - 487ms/epoch - 755us/step
Epoch 55/100
645/645 - 0s - loss: 1701.0400 - 463ms/epoch - 717us/step
Epoch 56/100
645/645 - 0s - loss: 1700.8654 - 494ms/epoch - 766us/step
Epoch 57/100
645/645 - 1s - loss: 1700.3434 - 538ms/epoch - 833us/step
Epoch 58/100
645/645 - 1s - loss: 1700.4766 - 564ms/epoch - 874us/step
Epoch 59/100
645/645 - 1s - loss: 1698.3831 - 527ms/epoch - 818us/step
Epoch 60/100
645/645 - 1s - loss: 1695.6500 - 532ms/epoch - 824us/step
Epoch 61/100
645/645 - 0s - loss: 1700.6793 - 452ms/epoch - 700us/step
Epoch 62/100
645/645 - 0s - loss: 1698.3130 - 500ms/epoch - 774us/step
Epoch 63/100
645/645 - 0s - loss: 1697.3019 - 496ms/epoch - 769us/step
Epoch 64/100
645/645 - 1s - loss: 1696.3141 - 555ms/epoch - 861us/step
Epoch 65/100
645/645 - 0s - loss: 1691.5929 - 472ms/epoch - 732us/step
Epoch 66/100
645/645 - 1s - loss: 1696.1968 - 606ms/epoch - 940us/step
Epoch 67/100
645/645 - 0s - loss: 1692.2610 - 481ms/epoch - 746us/step
Epoch 68/100
645/645 - 1s - loss: 1689.8152 - 582ms/epoch - 903us/step
Epoch 69/100
645/645 - 1s - loss: 1693.0546 - 537ms/epoch - 832us/step
Epoch 70/100
645/645 - 0s - loss: 1690.3346 - 475ms/epoch - 736us/step
Epoch 71/100
645/645 - 0s - loss: 1693.8423 - 482ms/epoch - 748us/step
Epoch 72/100
645/645 - 0s - loss: 1691.3414 - 464ms/epoch - 719us/step
Epoch 73/100
645/645 - 0s - loss: 1690.3364 - 465ms/epoch - 721us/step
Epoch 74/100
645/645 - 0s - loss: 1691.2177 - 452ms/epoch - 701us/step
Epoch 75/100
645/645 - 0s - loss: 1687.5054 - 463ms/epoch - 718us/step
Epoch 76/100
645/645 - 0s - loss: 1690.4796 - 462ms/epoch - 716us/step
Epoch 77/100
645/645 - 0s - loss: 1687.7722 - 460ms/epoch - 714us/step
Epoch 78/100
645/645 - 0s - loss: 1688.0629 - 456ms/epoch - 707us/step
Epoch 79/100
645/645 - 0s - loss: 1687.1816 - 488ms/epoch - 757us/step
Epoch 80/100
645/645 - 0s - loss: 1693.6367 - 488ms/epoch - 756us/step
Epoch 81/100
645/645 - 1s - loss: 1685.4890 - 528ms/epoch - 819us/step
Epoch 82/100
645/645 - 0s - loss: 1686.1119 - 453ms/epoch - 703us/step
Epoch 83/100
645/645 - 1s - loss: 1684.5210 - 575ms/epoch - 891us/step
Epoch 84/100
645/645 - 0s - loss: 1688.2133 - 479ms/epoch - 742us/step
Epoch 85/100
645/645 - 1s - loss: 1687.8354 - 707ms/epoch - 1ms/step
Epoch 86/100
645/645 - 1s - loss: 1686.0667 - 752ms/epoch - 1ms/step
Epoch 87/100
645/645 - 1s - loss: 1684.3223 - 712ms/epoch - 1ms/step
Epoch 88/100
645/645 - 1s - loss: 1685.3080 - 741ms/epoch - 1ms/step
Epoch 89/100
645/645 - 1s - loss: 1684.7653 - 596ms/epoch - 925us/step
Epoch 90/100
645/645 - 1s - loss: 1684.0507 - 613ms/epoch - 951us/step
Epoch 91/100
645/645 - 1s - loss: 1684.9386 - 557ms/epoch - 863us/step
Epoch 92/100
645/645 - 0s - loss: 1686.9042 - 458ms/epoch - 710us/step
Epoch 93/100
645/645 - 0s - loss: 1682.3337 - 459ms/epoch - 711us/step
Epoch 94/100
645/645 - 0s - loss: 1680.9252 - 486ms/epoch - 754us/step
Epoch 95/100
645/645 - 1s - loss: 1683.2983 - 501ms/epoch - 776us/step
Epoch 96/100
645/645 - 0s - loss: 1683.5116 - 494ms/epoch - 766us/step
Epoch 97/100
645/645 - 0s - loss: 1680.8197 - 492ms/epoch - 763us/step
Epoch 98/100
645/645 - 0s - loss: 1683.1365 - 484ms/epoch - 750us/step
Epoch 99/100
645/645 - 0s - loss: 1685.0138 - 495ms/epoch - 767us/step
Epoch 100/100
645/645 - 1s - loss: 1682.0463 - 522ms/epoch - 810us/step

In [26]:
# len(EOL3)

In [27]:
ann_pred = ann.predict(scaled_test_data[1:5001])

157/157 [==============================] - 0s 822us/step

In [28]:
from sklearn.metrics import r2_score

In [29]:
r2_score(EOL6[1:5001],ann_pred)

-0.09765935243690493